### ISSUE TITLE
Use Gitbook? :)

### ISSUE THREAD

**Issue by rakeshmenon** [dexteryy/spellbook-of-modern-webdev#84] opened 2017-06-22 04:12 UTC
Thank you for these awesome resources. Just a suggestion that using Gitbook format would help in organizing this better.

**Comment by dexteryy** [comment] 2017-06-23 06:05
Thanks for the suggestion. 

Duplicate of issue https://github.com/dexteryy/spellbook-of-modern-webdev/issues/6

**Closed by dexteryy** 2017-06-23 06:05 UTC
