### ISSUE TITLE
Suggestion: Use are.na to realize `knowledge graph`

### ISSUE THREAD

**Issue by r1b** [dexteryy/spellbook-of-modern-webdev#11] opened 2017-06-21 01:23 UTC
> I wish this document could be closer to a kind of knowledge graph or skill tree than a list or a collection.

I suggest that you try out [Arena](https://www.are.na/). It allows you to organize links & files in a graph.

**Comment by dexteryy** [comment] 2017-06-23 06:05
Thanks for the suggestion. It's very enlightening.

Duplicate of issue https://github.com/dexteryy/spellbook-of-modern-webdev/issues/6

**Closed by dexteryy** 2017-06-23 06:05 UTC
